server:
  port: 7002
spring:
  application:
    name: eureka-consumer

eureka:
  instance:
    prefer-ip-address: true # 用于设置是否显示主机的IP
  client:
    service-url:
      defaultZone: http://server1:7000/eureka/, http://server2:7009/eureka/
