server:
  port: 8835
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
zuul:
  routes:
    eureka-consumer:
      path: /eureka-consumer/**     #Zuul路由的前缀