server:
  port: 8761
spring:
  application:
    name: eureka-server   # 端口号名称配置
eureka:
  client:
    fetch-registry: false   # 表示是否向EurekaServer注册
    register-with-eureka: false # 表示是否从EurekaServer获取注册信息
    service-url:
      defaultZone: http://localhost:7009/eureka/
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
